PN-9773: core/confinfo complete pipeline

diff --git a/cd-cli/cnf-templates/complete-pipeline.yaml b/cd-cli/cnf-templates/complete-pipeline.yaml
--- a/cd-cli/cnf-templates/complete-pipeline.yaml
+++ b/cd-cli/cnf-templates/complete-pipeline.yaml
@@ -618,7 +618,30 @@ Resources:
               OutputArtifacts:
                 - Name: DesiredCommitIdsAndScripts
               RunOrder: 1
-            
+
+            # Verify Parameters
+            - Name: Verify_Parameters
+              ActionTypeId:
+                Category: Build
+                Owner: AWS
+                Version: 1
+                Provider: CodeBuild
+              Configuration:
+                ProjectName: !Ref CheckParametersCodebuildProject
+                PrimarySource: EmptyZip
+                EnvironmentVariables: !Sub '[
+                    {"name":"EnvName", "value":"${EnvName}", "type":"PLAINTEXT"},
+                    {"name":"AwsRegion", "value":"${AWS::Region}", "type":"PLAINTEXT"},
+                    {"name":"DesiredCommitIdsBucketName", "value":"${CdArtifactBucket}", "type":"PLAINTEXT"},
+                    {"name":"DesiredCommitIdsPath", "value":"config/desired-commit-ids-env.sh", "type":"PLAINTEXT"},
+                    {"name":"DesiredCommitIdsVersionId", "value":"#{DesiredCommitIdsNS.VersionId}", "type":"PLAINTEXT"}
+                  ]'
+              InputArtifacts:
+                - Name: EmptyZip
+              OutputArtifacts:
+                - Name: DesiredCommitIdsAndScripts
+              RunOrder: 2
+
             # UpdateInfrastructure AND AuthFleet
             - Name: Update_Infrastructure
               ActionTypeId:
@@ -639,7 +662,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: InfraOutput
-              RunOrder: 2
+              RunOrder: 3
             
             # Update pn-delivery
             - Name: Update_PnDelivery
@@ -664,7 +687,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnDeliveryOutput
-              RunOrder: 3
+              RunOrder: 4
             
             # Update pn-delivery-push
             - Name: Update_PnDeliveryPush
@@ -689,7 +712,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnDeliveryPushOutput
-              RunOrder: 3
+              RunOrder: 4
             
             # Update pn-mandate
             - Name: Update_PnMandate
@@ -714,7 +737,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnMandateOutput
-              RunOrder: 3
+              RunOrder: 4
             
             # Update pn-external-registries
             - Name: Update_ExternalRegistries
@@ -739,7 +762,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnExternalRegistriesOutput
-              RunOrder: 3
+              RunOrder: 4
             
             # Update pn-UserAttributes
             - Name: Update_UserAttributes
@@ -764,7 +787,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnUserAttributesOutput
-              RunOrder: 3
+              RunOrder: 4
             
             # Update pn-downtime-logs
             - Name: Update_DowntimeLogs
@@ -789,7 +812,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnDowntimeLogsOutput
-              RunOrder: 3
+              RunOrder: 4
             
             # # Update pn-radd-fsu
             # - Name: Update_RaddFsu
@@ -839,7 +862,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnLogsaverBeOutput
-              RunOrder: 3
+              RunOrder: 4
 
             # Update pn-national-registries
             - Name: Update_NationalRegistries
@@ -864,7 +887,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnNationalRegistriesOutput
-              RunOrder: 3
+              RunOrder: 4
 
             # Update pn-apikey-manager
             - Name: Update_ApiKeyManager
@@ -889,7 +912,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnApiKeyManagerOutput
-              RunOrder: 3
+              RunOrder: 4
 
             # Update pn-paper-channel
             - Name: Update_PaperChannel
@@ -914,7 +937,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnPaperChannelOutput
-              RunOrder: 3
+              RunOrder: 4
 
             # Update pn-kafka-bridge
             - Name: Update_KafkaBridge
@@ -939,7 +962,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnKafkaBridgeOutput
-              RunOrder: 3
+              RunOrder: 4
 
             # Update pn-progression-sensor
             - Name: Update_ProgressionSensor
@@ -964,7 +987,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnProgressionSensorOutput
-              RunOrder: 3
+              RunOrder: 4
 
             # Update pn-zendesk-auth
             - Name: Update_ZendeskAuth
@@ -989,7 +1012,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnZendeskAuthOutput
-              RunOrder: 3
+              RunOrder: 4
 
             # Update pn-logextractor-be
             - Name: Update_LogextractorBe
@@ -1014,7 +1037,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnLogextractorBeOutput
-              RunOrder: 3
+              RunOrder: 4
               
             # Update pn-f24
             - Name: Update_PnF24
@@ -1039,7 +1062,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnF24Output
-              RunOrder: 3
+              RunOrder: 4
 
             # Update pn-service-desk
             - Name: Update_PnServiceDesk
@@ -1064,7 +1087,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnServiceDeskOutput
-              RunOrder: 3
+              RunOrder: 4
 
             # Update pn-radd-alt
             - Name: Update_PnRaddAlt
@@ -1089,7 +1112,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnRaddAltOutput
-              RunOrder: 3
+              RunOrder: 4
 
             # Update pn-bff
             - Name: Update_PnBff
@@ -1114,7 +1137,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PnBffOutput
-              RunOrder: 3
+              RunOrder: 4
 
             # Update Frontend
             - Name: Update_Frontend
@@ -1136,7 +1159,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: FrontEndOutput
-              RunOrder: 4
+              RunOrder: 5
             
             # Update Helpdesk FE
             - Name: Update_HelpdeskFE
@@ -1158,7 +1181,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: HelpdeskFeOutput
-              RunOrder: 4
+              RunOrder: 5
 
             # Update logs and Usage Plans
             - Name: Infrastructure_Post_Deploy
@@ -1180,7 +1203,7 @@ Resources:
                 - Name: DesiredCommitIdsAndScripts
               OutputArtifacts:
                 - Name: PostDeployScriptsOutput
-              RunOrder: 4
+              RunOrder: 5
 
             # Run test if the environment is dev
             - Fn::If:
@@ -1201,7 +1224,7 @@ Resources:
                       ]'
                   InputArtifacts:
                     - Name: EmptyZip
-                  RunOrder: 5
+                  RunOrder: 6
                 - !Ref AWS::NoValue
             
             - Fn::If:
@@ -1221,7 +1244,7 @@ Resources:
                       ]'
                   InputArtifacts:
                     - Name: EmptyZip
-                  RunOrder: 5
+                  RunOrder: 6
                 - !Ref AWS::NoValue
             
             # List versions if the environment is dev
@@ -1243,7 +1266,7 @@ Resources:
                       ]'
                   InputArtifacts:
                     - Name: EmptyZip
-                  RunOrder: 6
+                  RunOrder: 7
                 - !Ref AWS::NoValue
 
 
@@ -1995,7 +2018,9 @@ Resources:
             Action: secretsmanager:GetSecretValue
             Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*
           - Effect: Allow
-            Action: ssm:GetParameters
+            Action: 
+              - ssm:GetParameters
+              - ssm:GetParameter
             Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*
           - Effect: Allow
             Action:
@@ -6282,6 +6307,84 @@ Resources:
       LogGroupName: !Sub "/aws/codebuild/${RunTestsFeCodebuildProject}"
       RetentionInDays: 14
 
+    # CODEBUILD used to download scripts
+  ###################################################
+  CheckParametersCodebuildProject:
+    Type: 'AWS::CodeBuild::Project'
+    Properties:
+      Name: !Sub ${ProjectName}-CheckParametersCodebuildProject
+      ServiceRole: !GetAtt CodeBuildRole.Arn
+      Source: 
+        Type: CODEPIPELINE
+        BuildSpec: |
+          version: 0.2
+
+          phases:
+            pre_build:
+              commands:
+                - echo "NO PRE_BUILD"
+            build:
+              commands:
+                - 'echo "### ENVIRONMENT ###"'
+                - 'echo "###################"'
+                - env
+                - 'echo ""'
+                - | 
+                  aws s3api get-object --bucket ${DesiredCommitIdsBucketName} --key ${DesiredCommitIdsPath} desired-commit-ids-env.sh --version-id ${DesiredCommitIdsVersionId}
+                  cat desired-commit-ids-env.sh
+                  echo "### DOWNLOAD DESIRED COMMIT IDS ###"
+                  echo ""
+                  echo "### SOURCE DESIRED COMMIT IDS ###"
+                  . ./desired-commit-ids-env.sh  
+                  echo ""
+                  echo ""
+                  echo "### UPDATED ENVIRONMENT ###"
+                  echo "###########################"
+                  env
+                  echo "### CLONE CICD SCRIPTS ###"
+                  echo ""
+                  git clone https://github.com/pagopa/pn-cicd.git
+                  ( cd pn-cicd && git checkout $cd_scripts_commitId )
+                  if ( [ ! -z "$PnConfigurationEnabled" ] ) then
+                    echo "### Execute Download Custom Config ###"
+                    ./pn-cicd/cd-cli/downloadParametersConfig.sh -r $AwsRegion -e $EnvName -w $(pwd) -c main -i $CiAccountId || exit 1
+                    echo ""
+                  else
+                    ./pn-cicd/cd-cli/downloadParametersConfig.sh -r $AwsRegion -e $EnvName -w $(pwd) || exit 1
+                  fi                 
+                - 'echo ""'
+                - 'echo "INSTALLING node_modules"'
+                - '(cd ./pn-cicd/cd-cli/validateParameters/ && npm i )'
+                - 'echo "./pn-cicd/cd-cli/validateParameters/ && node index.js --envName ${EnvName} --account core --parametersPath ../../../parameters/"'
+                - '(cd ./pn-cicd/cd-cli/validateParameters/ && node index.js --envName $EnvName --account core --parametersPath ../../../parameters/) '
+                - |
+                  if [ -f ./pn-cicd/cd-cli/validateParameters/results/output.log ]; then
+                    echo "Error: Issues found in parameter validation."
+                    cat ./pn-cicd/cd-cli/validateParameters/results/output.log
+                    exit 1
+                  else
+                    echo "All parameters are syncs"
+                  fi
+          artifacts:
+            files:
+              - 'scripts/**/*'
+      Artifacts:
+        Type: CODEPIPELINE
+      Environment:
+        ComputeType: BUILD_GENERAL1_SMALL
+        Type: LINUX_CONTAINER
+        Image: "aws/codebuild/standard:7.0"
+        EnvironmentVariables:
+          - Name: PnConfigurationEnabled
+            Type: PLAINTEXT
+            Value: !If [ IsNewConfiguration, 'main', '' ]
+          - Name: CiAccountId
+            Type: PLAINTEXT
+            Value: !Ref CiAccountId
+          - Name: Account
+            Type: PLAINTEXT
+            Value: 'core'
+        
 Outputs:
   CdArtifactBucketName:
     Value: !Ref CdArtifactBucket
diff --git a/cd-cli/cnf-templates/confinfo-complete-pipeline.yaml b/cd-cli/cnf-templates/confinfo-complete-pipeline.yaml
--- a/cd-cli/cnf-templates/confinfo-complete-pipeline.yaml
+++ b/cd-cli/cnf-templates/confinfo-complete-pipeline.yaml
@@ -16,6 +16,11 @@ Parameters:
     Description: 'AWS AccountID used for C.I. tasks'
     Type: String
 
+  Account:
+    Default: 'confinfo'
+    Description: 'Account environment'
+    Type: String
+
   CiArtifactBucketNameParam:
     Default: 'pn-ci-root-ciartifactbucket-k7htwr5id1op'
     Description: 'Bucket name containing lambda and frontend artifacts'
@@ -430,7 +435,30 @@ Resources:
               OutputArtifacts:
                 - Name: DesiredCommitIdsAndScripts
               RunOrder: 1
-            
+
+            # Verify Parameters
+            - Name: Verify_Parameters
+              ActionTypeId:
+                Category: Build
+                Owner: AWS
+                Version: 1
+                Provider: CodeBuild
+              Configuration:
+                ProjectName: !Ref CheckParametersCodebuildProject
+                PrimarySource: EmptyZip
+                EnvironmentVariables: !Sub '[
+                    {"name":"EnvName", "value":"${EnvName}", "type":"PLAINTEXT"},
+                    {"name":"AwsRegion", "value":"${AWS::Region}", "type":"PLAINTEXT"},
+                    {"name":"DesiredCommitIdsBucketName", "value":"${CdArtifactBucket}", "type":"PLAINTEXT"},
+                    {"name":"DesiredCommitIdsPath", "value":"config/desired-commit-ids-env.sh", "type":"PLAINTEXT"},
+                    {"name":"DesiredCommitIdsVersionId", "value":"#{DesiredCommitIdsNS.VersionId}", "type":"PLAINTEXT"}
+                  ]'
+              InputArtifacts:
+                - Name: EmptyZip
+              OutputArtifacts:
+                - Name: DesiredCommitIdsAndScripts
+              RunOrder: 2
+
             # Update pn-infra
             - Name: Update_Infrastructure
               ActionTypeId:
@@ -1771,6 +1799,82 @@ Resources:
         Type: LINUX_CONTAINER
         Image: "aws/codebuild/standard:6.0"
 
+  CheckParametersCodebuildProject:
+    Type: 'AWS::CodeBuild::Project'
+    Properties:
+      Name: !Sub ${ProjectName}-CheckParametersCodebuildProject
+      ServiceRole: !GetAtt CodeBuildRole.Arn
+      Source: 
+        Type: CODEPIPELINE
+        BuildSpec: |
+          version: 0.2
+
+          phases:
+            pre_build:
+              commands:
+                - echo "NO PRE_BUILD"
+            build:
+              commands:
+                - 'echo "### ENVIRONMENT ###"'
+                - 'echo "###################"'
+                - env
+                - 'echo ""'
+                - | 
+                  aws s3api get-object --bucket ${DesiredCommitIdsBucketName} --key ${DesiredCommitIdsPath} desired-commit-ids-env.sh --version-id ${DesiredCommitIdsVersionId}
+                  cat desired-commit-ids-env.sh
+                  echo "### DOWNLOAD DESIRED COMMIT IDS ###"
+                  echo ""
+                  echo "### SOURCE DESIRED COMMIT IDS ###"
+                  . ./desired-commit-ids-env.sh  
+                  echo ""
+                  echo ""
+                  echo "### UPDATED ENVIRONMENT ###"
+                  echo "###########################"
+                  env
+                  echo "### CLONE CICD SCRIPTS ###"
+                  echo ""
+                  git clone https://github.com/pagopa/pn-cicd.git
+                  ( cd pn-cicd && git checkout $cd_scripts_commitId )
+                  if ( [ ! -z "$PnConfigurationEnabled" ] ) then
+                    echo "### Execute Download Custom Config ###"
+                    ./pn-cicd/cd-cli/downloadParametersConfig.sh -r $AwsRegion -e $EnvName -w $(pwd) -c main -i $CiAccountId || exit 1
+                    echo ""
+                  else
+                    ./pn-cicd/cd-cli/downloadParametersConfig.sh -r $AwsRegion -e $EnvName -w $(pwd) || exit 1
+                  fi                 
+                - 'echo ""'
+                - 'echo "INSTALLING node_modules"'
+                - '(cd ./pn-cicd/cd-cli/validateParameters/ && npm i )'
+                - 'echo "./pn-cicd/cd-cli/validateParameters/ && node index.js --envName ${EnvName} --account $Account --parametersPath ../../../parameters/"'
+                - '(cd ./pn-cicd/cd-cli/validateParameters/ && node index.js --envName $EnvName --account $Account --parametersPath ../../../parameters/) '
+                - |
+                  if [ -f ./pn-cicd/cd-cli/validateParameters/results/output.log ]; then
+                    echo "Error: Issues found in parameter validation."
+                    cat ./pn-cicd/cd-cli/validateParameters/results/output.log
+                    exit 1
+                  else
+                    echo "All parameters are syncs"
+                  fi
+          artifacts:
+            files:
+              - 'scripts/**/*'
+      Artifacts:
+        Type: CODEPIPELINE
+      Environment:
+        ComputeType: BUILD_GENERAL1_SMALL
+        Type: LINUX_CONTAINER
+        Image: "aws/codebuild/standard:7.0"
+        EnvironmentVariables:
+          - Name: PnConfigurationEnabled
+            Type: PLAINTEXT
+            Value: !If [ IsNewConfiguration, 'main', '' ]
+          - Name: CiAccountId
+            Type: PLAINTEXT
+            Value: !Ref CiAccountId
+          - Name: Account
+            Type: PLAINTEXT
+            Value: 'confinfo'
+
   CodeBuildRole:
     Type: AWS::IAM::Role
     Properties:
@@ -1878,7 +1982,9 @@ Resources:
             Action: secretsmanager:GetSecretValue
             Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*
           - Effect: Allow
-            Action: ssm:GetParameters
+            Action: 
+              - ssm:GetParameters
+              - ssm:GetParameter
             Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*
           - Effect: Allow
             Action:
